import type { AppModel } from '@sheplang/language';

const typeMap: Record<string, string> = {
  'text': 'string',
  'number': 'number',
  'yes/no': 'boolean',
  'id': 'string',
  'date': 'string',
  'email': 'string'
};

function toTsType(s: string): string {
  return typeMap[s] ?? 'unknown';
}

export function templateTsConfig(): string {
  return `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "strict": true,
    "jsx": "react-jsx",
    "noEmit": true
  },
  "include": ["**/*.ts", "**/*.tsx"]
}`;
}

export function templateModels(app: AppModel): { path: string; content: string }[] {
  return app.datas.map(d => {
    const fields = d.fields.map((f: { name: string; type: string }) => `  ${f.name}: ${toTsType(f.type)};`).join('\n');
    const rules = d.rules.length ? `// rules:\n// ${d.rules.map((r: string) => `- ${r}`).join('\n// ')}` : `// rules: (none)`;
    const content = `// Auto-generated by ShepLang
export type ${d.name} = {
${fields}
};
${rules}
`;
    return { path: `models/${d.name}.ts`, content };
  });
}

export function templateActions(app: AppModel): { path: string; content: string }[] {
  return app.actions.map(a => {
    const paramsSig = a.params.map((p: { name: string; type?: string }) => `${p.name}${p.type ? `: ${toTsType(p.type)}` : ': any'}`).join(', ');
    const ops = a.ops.map((op: { kind: string; data?: string; view?: string; text?: string; fields?: Record<string, string> }) => {
      if (op.kind === 'add' && op.fields && op.data) {
        const pairs = Object.entries(op.fields).map(([k, v]) => `${k}: ${v}`).join(', ');
        return `  // add ${op.data}\n  console.log("db.create", { ${pairs} });`;
      }
      if (op.kind === 'show' && op.view) {
        return `  // show ${op.view}\n  console.log("navigate -> ${op.view}");`;
      }
      return `  // raw\n  console.log(${JSON.stringify(op.text || '')});`;
    }).join('\n');

    const content = `// Auto-generated by ShepLang
export async function ${a.name}(${paramsSig}) {
${ops || '  // no-ops'}
}
`;
    return { path: `actions/${a.name}.ts`, content };
  });
}

export function templateViews(app: AppModel): { path: string; content: string }[] {
  return app.views.map((v: { name: string; list?: string; buttons: Array<{ label: string; action: string }> }) => {
    const list = v.list ? `console.log("List ${v.list} []");` : '';
    const btns = v.buttons.map((b: { label: string; action: string }) => `console.log("Button ${b.label} -> ${b.action}");`).join('\n');
    const content = `// Auto-generated by ShepLang
export function ${v.name}() {
  ${list}
  ${btns}
  return null; // placeholder UI; React-friendly signature
}
`;
    return { path: `views/${v.name}.ts`, content };
  });
}

export function templateIndex(app: AppModel): { path: string; content: string } {
  const imports: string[] = [];
  app.views.forEach((v: { name: string }) => imports.push(`import { ${v.name} } from './views/${v.name}';`));
  app.actions.forEach((a: { name: string }) => imports.push(`import { ${a.name} } from './actions/${a.name}';`));

  const run = `export async function run() {
  console.log("Starting ${app.name}…");
  ${app.views.map((v: { name: string }) => `if (${v.name}) ${v.name}();`).join('\n  ')}
}`;

  return {
    path: `index.ts`,
    content: `// Auto-generated by ShepLang
${imports.join('\n')}

${run}
`
  };
}
